name: kendana

services:

  # --- DATABASE (POSTGRESQL) ---
  db:
    image: postgres:15-alpine
    container_name: laravel_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE:-bendaharaku}
      POSTGRES_USER: ${DB_USERNAME:-sail}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - finance_net

networks:
  finance_net:
    driver: bridge

volumes:
  db_data:
